### ISSUE TITLE
Support Rails 7.1

### ISSUE THREAD

**Issue by vseguin** [doctolib/safe-pg-migrations#127]
Hi 👋

https://github.com/doctolib/safe-pg-migrations/blob/master/Gemfile.lock - the Gemfile is preventing to upgrade to Rails 7.1, as both `activerecord` and `activesupport` are currently specified as `< 7.1`. Would be great to update this with Rails's new version.

**Comment by vseguin** [comment]
Hello @CharlesDelannoy 👋 

Wondering, any plans to do this? We'd like to upgrade our app to Rails 7.1 and this is a blocker - and we would like to keep the lib! Also happy to submit a PR if you think this is the best course of action!

**Comment by beauraF** [comment]
Thanks @vseguin, it's now fixed by https://github.com/doctolib/safe-pg-migrations/pull/133.
