### ISSUE TITLE
Support default value on a table where id is a UUID

### ISSUE THREAD

**Issue by DrPlop** [doctolib/safe-pg-migrations#3]
#### Current state
`safe-pg-migrations` doesn't support to add a default value on table with a UUID primary key.

If you do, you will get the following error:
```
PG::UndefinedFunction: ERROR:  operator does not exist: uuid > integer
LINE 1: SELECT id FROM "mytable" WHERE id > 0 ORDER BY id LIMIT 10...
```
This issue is related to [this line.](https://github.com/doctolib/safe-pg-migrations/blob/master/lib/safe-pg-migrations/plugins/statement_insurer.rb#L58)

#### What is the expected behavior?

That `safe-pg-migrations` supports both integer and uuid for primary key id.

**Comment by Gpotet** [comment]
To close?

**Comment by DrPlop** [comment]
> To close?

If you don't need this feature anymore, you can definitively close this old PR

**Comment by ThHareau** [comment]
I believe this issue is still a real problem; with a UUID as a primary key (or actually with any table whose primary key is not an integer named `id`), backfilling the default value would not work. 

On the other hand, this method is only used with old versions of PG. Fixing the library is tricky here, a better solution would be to simply update the README, indicating that a numeric primary key named `id` is required for having the backfill work.

**Comment by mikatuo** [comment]
Is there a way to disable the backfill in batches logic? Most of our tables have uuid as primary keys which would make using of this gem impossible :(

**Comment by rchoquet** [comment]
Hey @mikatuo, which version of PG are you using? If you are using PG11+ this logic is disabled as it's handled by PG itself.
If not, we should adapt the backfill logic to make it work with uuid primary keys.

**Comment by mikatuo** [comment]
9.6

**Comment by pablosole** [comment]
Hi there, just found this issue and it affects me too. I'm using PSQL 10.12 so the new logic didn't kick in either.

**Comment by ThHareau** [comment]
A good solution for that would be to rely on [BatchEnumerator](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/relation/batches/batch_enumerator.rb) or directly [in_batches](https://github.com/rails/rails/blob/db9209df246ea2d713478f27203d01acc21c8c13/activerecord/lib/active_record/relation/batches.rb#L204), in the method `backfill_column_default`

I am not planning to work on it soon, but I'd be happy to review a PR :)

**Comment by ThHareau** [comment]
Hey @mikatuo, @pablosole and maybe @DrPlop, I merged a PR which should solve the issue, can you tell me if it solves your issue? 

I'm about to release a new version of the gem, but if you want to try it sooner you should rely on the last commit
