### ISSUE TITLE
Wrong number of arguments - Rails 6.1

### ISSUE THREAD

**Issue by Laykou** [doctolib/safe-pg-migrations#41]
When using with Rails 6.1 I receive a lot of times error:

```
StandardError: An error has occurred, all later migrations canceled:

wrong number of arguments (given 4, expected 3)
```

Migration:

```ruby
add_column :actions, :approval_level_id, :bigint, index: true
```

Is this gem compatible with latest Rails release?

**Comment by rchoquet** [comment]
Hello,

I don't think `index` is a valid option for `add_column`, does not seem to work on my side even without `safe-pg-migrations`.
I would advise to either use `add_reference` or ` add_column` + `add_index`

**Comment by ThHareau** [comment]
Hey @Laykou, I'm closing this issue as it seems it is not related to this gem. Feel free to reopen it if needed.
