### ISSUE TITLE
Can't rollback an add_index migration

### ISSUE THREAD

**Issue by ylansegal** [doctolib/safe-pg-migrations#44]
This gem is a fantastic idea! Thank you for the work to make it available to the community.

I'm attempting to use it in a project, and ran into an issue straight away. 

```
$ bundle info safe-pg-migrations
  * safe-pg-migrations (1.2.3)
	Summary: Make your PG migrations safe.
	Homepage: https://github.com/doctolib/safe-pg-migrations
	Path: /Users/ylansegal/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/safe-pg-migrations-1.2.3
```

Here is my test migration:

```ruby
class AddTestIndex < ActiveRecord::Migration[6.1]
  def change
    add_index :users, :created_at
  end
end
```

I can run `db:migrate` and see the expected safe operations for concurrently:

```
$ rails db:migrate
== 20210617192601 AddTestIndex: migrating =====================================
-- add_index(:users, :created_at)
   -> add_index("users", :created_at, {:algorithm=>:concurrently})
   -> 0.0087s
== 20210617192601 AddTestIndex: migrated (0.0118s) ============================
```

However, I encounter an error when I try to rollback:

```
$ rails db:rollback
== 20210617192601 AddTestIndex: reverting =====================================
-- remove_index(:users, :created_at)
   -> remove_index("users", {:column=>:created_at, :algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

No indexes found on users with the options provided.

Caused by:
ArgumentError: No indexes found on users with the options provided.
```

Thank you!

**Comment by ylansegal** [comment]
I am using Rails 6.1:

```
$ bundle info rails
  * rails (6.1.3.2)
	Summary: Full-stack web application framework.
	Homepage: https://rubyonrails.org
	Documentation: https://api.rubyonrails.org/v6.1.3.2/
	Source Code: https://github.com/rails/rails/tree/v6.1.3.2
	Changelog: https://github.com/rails/rails/releases/tag/v6.1.3.2
	Bug Tracker: https://github.com/rails/rails/issues
	Mailing List: https://discuss.rubyonrails.org/c/rubyonrails-talk
	Path: /Users/ylansegal/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/rails-6.1.3.2
```

And should note that even `create_table` migrations don't work on a new rails app:

```ruby
```

**Comment by rchoquet** [comment]
Hey @ylansegal ! Thanks for the issues report, and sorry that you did not have the best experience with safe-pg-migrations 😢 

We will investigate what could be the root cause.

In the meantime, could you try to reproduce the issues you encountered using the branch from https://github.com/doctolib/safe-pg-migrations/pull/43? It adds support for Ruby 3.

**Comment by ylansegal** [comment]
@rchoquet That did the trick. Both migrations ran successfully on that branch!

**Comment by Izzette** [comment]
@rchoquet is it possible to update the versioning requirement for older versions of the gem so that others don't have the same problem as @ylansegal ?

**Comment by ThHareau** [comment]
I can do that

**Comment by ylansegal** [comment]
Version `1.3.0` of the gem fixes my original issue. Thank you so much. Keep up the good work!

**Comment by ThHareau** [comment]
You're welcome, thanks for reporting this issue :)
