### ISSUE TITLE
Adding a foreign key causes `ArgumentError: unknown keyword: :column`

### ISSUE THREAD

**Issue by Eschults** [doctolib/safe-pg-migrations#59]
Hello 👋 

First of all thank you for sharing this very handy gem which works _out of the box_ and solves such a great pain 🙌 

**Problem**
I ran into an issue using the latest `1.3.0` version of the gem on a ruby `2.7.4` rails `5.2.6` project.
Adding a foreign key to a table with `add_reference` triggered an `ArgumentError: unknown keyword: :column` when running `rails db:migrate`. I reproduced the error on a vanilla [`rails new` project](https://github.com/Eschults/safe-pg-add-reference/commits/master) with the same versions to let you reproduce the 🐛  easily 👌 
Here is the backtrace 👇 

```bash
== 20211015145629 AddRestaurantReferenceToReviews: migrating ==================
-- add_reference(:reviews, :restaurant, {:foreign_key=>true})
   -> add_index("reviews", ["restaurant_id"], {:algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

unknown keyword: :column
/Users/edwardschults/code/Eschults/safe-pg-add-reference/db/migrate/20211015145629_add_restaurant_reference_to_reviews.rb:3:in `change'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/rails:9:in `<top (required)>'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'

Caused by:
ArgumentError: unknown keyword: :column
/Users/edwardschults/code/Eschults/safe-pg-add-reference/db/migrate/20211015145629_add_restaurant_reference_to_reviews.rb:3:in `change'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/rails:9:in `<top (required)>'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

After debugging and `step`-ping in the source code, I found out that the error was coming from [this line](https://github.com/doctolib/safe-pg-migrations/blob/55a46708ef955e174b245a42a1ae78b404616433/lib/safe-pg-migrations/plugins/idempotent_statements.rb#L40), which [changed between `1.2.3` and `1.3.0`](https://github.com/doctolib/safe-pg-migrations/compare/v1.2.3...v1.3.0) with the addition of support for Ruby 3.0.

Note that when this error occurs, the creation of the column _actually goes through_, but not the creation of the `schema_migrations` record, making any new `rails db:migrate` run into the error again and preventing next migrations to run.

**Solution**
Downgrading to `1.2.3` solves the error on ruby 2.7 👌 

Cheers!

**Comment by ThHareau** [comment]
Hello @Eschults, first I'd like to apologize for answering that late to your issue. 

The problem should be fixed; it is a compatibility issue with rails 5.2. I will release a new version next week fixing this issue.

Feel free to open another issue if you see any further difficulty with compatibility on rails 5.2, we don't use this version of rails anymore, so we wouldn't see it.
