### ISSUE TITLE
question: Is there a way to disable logging for some migrations?

### ISSUE THREAD

**Issue by ChrisCPO** [doctolib/safe-pg-migrations#84]
We chose to go with this gem over strong-migrations because of the nicer logging. However if does not play well with a Gem called [data-migrate](https://github.com/ilyakatz/data-migrate). In the sense that the logging is really verbose, where updating thousands of records will create tens of thousands of migration logs. 

So is there a way to disable the logging for some migrations but not others perhaps a class method or option ?

**Comment by rchoquet** [comment]
Hello @ChrisCPO! Not with the current implementation, but it indeed seems a legit use case for data migrations.

What do you think about this API?

```ruby
# frozen_string_literal: true

class MyMigration < ActiveRecord::Migration[7.0]
  safe_pg_migrations_verbose false

  def change
    ...
  end
end
```

**Comment by ChrisCPO** [comment]
@rchoquet thanks for the quick response. 

Seems like a great API!

**Comment by ThHareau** [comment]
Hi @ChrisCPO 🙂  I've just merged the implementation above. Tell us if it suits your needs

**Comment by ChrisCPO** [comment]
@ThHareau thank you! Will check it out this week
