### ISSUE TITLE
safe rename_column seems to be missing?

### ISSUE THREAD

**Issue by ChrisCPO** [doctolib/safe-pg-migrations#85]
Rename column is missing from the safe rails methods, is this intended?
https://github.com/doctolib/safe-pg-migrations/blob/267c2b72020757e9a85c757e7d377e804f6174da/lib/safe-pg-migrations/base.rb#L84-L92

I ask because the alter table statement to rename a column will need an access exclusive lock, no?

rails also drops and recreates the index, using `add_index` which is a safe method. 

https://github.com/rails/rails/blob/18da7b6ba71c5ae2ed212e9f3a9e8f6dd0732b12/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L462-L466

Based on all of this, but I could be missing something, I would expect this gem to protect `rename_column`.

**Comment by ThHareau** [comment]
Hi @ChrisCPO, 

`safe-pg-migrations` doesn't make  `rename_column` safe. It is not something we could actually do, because it requires a management of retro-compatibility over several rollouts. 

Regarding the safe `execute`, it's a bit missleading. I need to check , but I think this was added because we use execute in the gem, and we don't want to have to add `safety_assured` around each `execute` in the gem. I'll explore a bit to see if we can be a bit more clever on that point

Regarding your question, it's more because strong_migration checks directly the [name of the current method](https://github.com/ankane/strong_migrations/blob/4a22176cb5e2cd320b365c6d2fb2ae0333caec78/lib/strong_migrations/checks.rb#L355). So even if `execute` is marked as safe, as long as  `rename_column` is not included in `SAFE_METHODS`, it would not be safe.

**Comment by ThHareau** [comment]
Hi @baueric. 

I will just quote https://github.com/ankane/strong_migrations#removing-a-column here, they are describing the retrocompatibility issue quite well: 

> #### Bad
> 
> Renaming a column that’s in use will cause errors in your application.
> 
> ```ruby
> class RenameSomeColumn < ActiveRecord::Migration[7.0]
>   def change
>     rename_column :users, :some_column, :new_name
>   end
> end
> ```
> 
> #### Good
> 
> A safer approach is to:
> 
> 1. Create a new column
> 2. Write to both columns
> 3. Backfill data from the old column to the new column
> 4. Move reads from the old column to the new column
> 5. Stop writing to the old column
> 6. Drop the old column

safe-pg-migrations is not able to solve this retrocompatibility, as it only acts on the context of one migration during one rollout. Here there are two rollouts needed: one between 3. and 4., one between 5. and 6.

---
> My main concern is doing a rename_column without a lock timeout, is it a limitation of postgres that we can't use a lock_timeout with an alter table rename column?

So you can definitively add a timeout around rename column, but this won't scale as you will still have some errors at some point.

**Comment by ThHareau** [comment]
Yes exactly, we cannot fix every issues of `strong_migrations` so we make sure both can be used together

**Comment by fatkodima** [comment]
A little self promotion: you can look at an alternative kinda "effortless" renaming of the tables/columns: https://github.com/fatkodima/online_migrations#renaming-a-column
That gem also supports lock retries - https://github.com/fatkodima/online_migrations#lock-timeout-retries.

**Comment by ChrisCPO** [comment]
@ThHareau
I'm still a little confused on:
>> My main concern is doing a rename_column without a lock timeout, is it a limitation of postgres that we can't use a lock_timeout with an alter table rename column?

> So you can definitively add a timeout around rename column, but this won't scale as you will still have some errors at some point.

What errors are normally raised here, are they from postgres or rails expecting the column name active record's attr_accessors etc? If it is rails, seems like a workaround could be to implement a custom reader/writer that checks for the right column name, but then why does rename column not take out an exclusive lock? Wait I think I understand it does take out an exclusive lock but the queued requests would have the old column name, not the new one, because these are opened before and in the lock queue with the old rails cache of the table schema?

**Comment by ThHareau** [comment]
@ChrisCPO @baueric yes it's exactly that. When you deploy your application, everything won't happen at once. With rails it will look like this: 

1. run migrations
2. update the code

Between steps 1 and 2, your application is in a weird shape: you have a database using the most recent schema definition, but the code is still using the old schema definition. If your migration is a rename_column, then the column was renamed, but the code is still using the old name.

If you database is small, steps 1 and 2 will happen very close to each other. So it probably doesn't matter. However, the bigger your database is, the longer each steps are taking.

**Comment by ThHareau** [comment]
I'll close this issue if it's ok, feel free to reopen if needed :)
